name: CI Workflow

on:
  push:
    branches: [main]

jobs:
  demo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: bootstrap-app/bootstrap

      - name: Run tests
        run: npm test
        working-directory: bootstrap-app/bootstrap